# Setup
title: 윤준영, 더불어 성장하는 개발자
url: https://getpoole.com
paginate: 1
baseurl: ""
permalink: /:categories/:title

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Junyeong Yun
  # url: https://twitter.com/mdo
  email: ypjun100@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
# nav:
#   - title: English
#     url: /en